<?php

/*
|--------------------------------------------------------------------------------------
| Render views.
|--------------------------------------------------------------------------------------
|
| This example aims to demonstrate how to use the Free-Blade template engine to render
| views of an application.
|
*/

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Include autoload.php generated by composer
require_once "../vendor/autoload.php";

// Includes the file that defines the constants
require_once "constants.php";

// Imports the class namespace
use FreeBlade\Template;

// Defines variables to be passed to the view
$params = array(
	"param1" => "Lorem ipsum",
	"param2" => "dolor sit amet"
);

// Render the view
Template::render("main", $params);

?>